name: Release
on:
  push:
    branches:
      - 'release'

jobs:
  increment:
    name: Auto-Increment Version
    runs-on: ubuntu-latest
    steps:
     - name: Auto Increment Semver Action
       uses: MCKanpolat/auto-semver-action@1.0.5
       id: versioning
       with:
         releaseType: patch 
         incrementPerCommit: false
         github_token: ${{ secrets.GH_TOKEN }}

     - name: Next Release Number
       run: echo ${{ steps.versioning.outputs.version }}
