name: Release
on:
  push:
    branches:
      - 'main'

jobs:
  match-pr-label:
    name: Match PR Label
    runs-on: ubuntu-latest
    steps:
      - uses: zwaldowski/match-label-action@v1
        with:
          allowed: major, minor, patch
