name: Release
on:
  pull_request:
    branches:
      - 'main'

jobs:   
  release:
    name: Create GH Release
    runs-on: ubuntu-latest
    steps:
      - name: bump_version
      - uses: christian-draeger/increment-semantic-version@1.0.2
        with:
          current-version: '0.0.1'
          version-fragment: 'bug'
      
      - name: Do something with your bumped release version
        run: echo ${{ steps.bump_version.outputs.next-version }}
      
#   - uses: zwaldowski/semver-release-action@v1
#       with:
#         dry_run: true
#         bump: ${{ steps.bump.outputs.version }}
#         github_token: ${{ secrets.GH_TOKEN }}
       # Do something to modify the repo using `${{ steps.bump.outputs.version }}`.
      - run: echo "${{ steps.bump.outputs.version }}"
      - run: |
          git add .
          git commit -m "Bump version"
          git push
          echo ::set-output name=sha::$(git rev-parse HEAD)
      - uses: zwaldowski/semver-release-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          sha: ${{ steps.git_commit.outputs.sha }}

